### ISSUE TITLE
Threat Intel Analyst

### ISSUE THREAD

**Issue by Lex1020** [r-cybersecurity/your-experience-starting-in-security#3]
Author: u/CrowGrandFather
Description: Threat Intelligence is a complementary service to help guide security operations. A threat intelligence analyst can be expected to research indicators of compromise, read reporting, and provide actionable courses of action. Threat Intelligence is incredibly difficult to do well but it a great place to learn the ins and outs of SOC work without the high stakes fast paced action of SOC work. I started in threat intelligence and I'm managing an incident response team now. 

Link: https://blog.gravitywall.net/2021/09/cybersecurity-project-how-i-broke-into-the-field/

**Comment by tweedge** [comment]
This is *excellent*!  Thank you - adding this to the directory! It'll be added to the wiki from there, and we'll put it in a normal rotation for promotion on Mentorship Monday
